### ISSUE TITLE
Problem decoding returned access token / JWT

### ISSUE THREAD

**Issue by shawnlauzon** [ecency/hivesigner-sdk#11]
I'm having a problem decoding the JWT returned as the access token on the server. The error I get with the Ruby library is `JWT::DecodeError (Not enough or too many segments)`. However, this can be verified with any online page which verifies a jwt, e.g. https://jwt.io/

![image](https://user-images.githubusercontent.com/611529/127057096-b2c39d29-63d9-4db6-b008-9d531b416247.png)

Can see the payload is `""`:
![image](https://user-images.githubusercontent.com/611529/127057418-27814b6a-1ea2-4510-995c-52a6a5d2aa90.png)

If I simply change the payload from `""` to '{}`, then both my code and https://jwt.io decode the token nicely.

I have no workaround for this, so a workout would be accepted while this is being resolved. Thank you.

**Comment by feruzm** [comment]
Did you try decoding access token like this? https://www.base64decode.net/ruby-base64-decode64

**Comment by shawnlauzon** [comment]
Ahh, that works much better. Thank you!
