### ISSUE TITLE
Use of the SDK against a local testnet

### ISSUE THREAD

**Issue by somq** [ecency/hivesigner-sdk#14]
I'm starting a dev and it appears that your SDK makes things quite easier, thanks for that!

Unfortunately I've not been able to reach the point where I can
- Either use a dev account on testnet (Could not find any UI to create one and the client throw a Cert invalid error when trying programmatically)
- Or use the local stack hivesigner SDK => hivesigner API => local testnet (Could not get the API talk to the local testnet: ECONNRESET @ http://127.0.0.1:8090/ though the Docker port is open)[

I've integrated the SDK to my client and I've successfully been able to bootstrap the API, though the API is unable to talk to the local testnet.

Here is the [Hivesigner API](https://github.com/ecency/hivesigner-api) log

```log
eyJza.<redacted access token>...
Didn't failover for error code: [ECONNRESET]
Get accounts failed FetchError: request to http://127.0.0.1:8090/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/clement/_dev/hive/dev_tests/hivesigner-api/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

At this point, I'm wondering if I should dev directly against the mainnet :/
I understand my question is kind of out of the scope of this repo but I'm having trouble finding accurate information on hive dev.
Any help would be appreciated!

**Comment by feruzm** [comment]
Did you try testnet.hivesigner.com? Of course you need to provide testnet RPC server that's alive and working. As far as I know, there is no public testnet instance right now. If your tests are small scale, doing direct test on mainnet is considered ok.
