### ISSUE TITLE
[QUESTION] Payment Decline

### ISSUE THREAD

**Issue by zackrspv** [ecency/hivesigner-sdk#21]
Using Hive Signer SDK, how do we specify a payment decline for a given post? Ergo, if the user wishes NOT to monetize the post, but still post it to the blockchain, we can usually specify 'decline payment' on hive.blog; but how can we do that via the SDK?

**Comment by feruzm** [comment]
@zackrspv Try `.sendOperations` method where you can include multiple operations in single call.
One operation will be post/content publishing operations, 2nd one will be comment_options operation that defines decline payouts settings. Let me know if it works

**Comment by zackrspv** [comment]
@feruzm do you have an example of that JSON element showing payment decline? I tried doing one on hive.blog and looking at the raw JSON that was posted onto the chain, but it's not there, even though it shows on the frontend.

**Comment by zackrspv** [comment]
Thanks, we have adjusted using the code above w/o issue.
